
version: 1
disable_existing_loggers: True

formatters:
    simple:
        format: '%(asctime)s [%(levelname)s] %(name)s: %(message)s'
        datefmt: '%Y-%m-%d_%H:%M:%S'

handlers:
    console:
        class: logging.StreamHandler
        level: DEBUG
        formatter: simple
        stream: ext://sys.stdout

    file:
        class: logging.FileHandler
        level: INFO
        formatter: simple
        filename: log/project.log
        mode: a

loggers:
    dev:
        level: DEBUG
        handlers: [console]
        propagate: no

    staging:
        level: INFO
        handlers: [console, file]
        propagate: no

    prod:
        level: WARNING
        handlers: [file]
        propagate: no

root:
    level: DEBUG
    handlers: [console]
